// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aliexpress_seller_token.sql

package sqldb

import (
	"context"
	"database/sql"
	"time"
)

const findAliExpressSellerTokenBySellerID = `-- name: FindAliExpressSellerTokenBySellerID :one
SELECT
    id,
    seller_id,
    havana_id,
    app_user_id,
    user_nick,
    account,
    account_platform,
    locale,
    sp,
    access_token,
    refresh_token,
    access_token_expires_at,
    refresh_token_expires_at,
    last_refreshed_at,
    authorized_at,
    created_at,
    updated_at
FROM gugu.aliexpress_seller_token
WHERE seller_id = $1
`

func (q *Queries) FindAliExpressSellerTokenBySellerID(ctx context.Context, sellerID string) (GuguAliexpressSellerToken, error) {
	row := q.db.QueryRowContext(ctx, findAliExpressSellerTokenBySellerID, sellerID)
	var i GuguAliexpressSellerToken
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.HavanaID,
		&i.AppUserID,
		&i.UserNick,
		&i.Account,
		&i.AccountPlatform,
		&i.Locale,
		&i.Sp,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.LastRefreshedAt,
		&i.AuthorizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOneAliExpressSellerToken = `-- name: FindOneAliExpressSellerToken :one
SELECT
    id,
    seller_id,
    havana_id,
    app_user_id,
    user_nick,
    account,
    account_platform,
    locale,
    sp,
    access_token,
    refresh_token,
    access_token_expires_at,
    refresh_token_expires_at,
    last_refreshed_at,
    authorized_at,
    created_at,
    updated_at
FROM gugu.aliexpress_seller_token
LIMIT 1
`

func (q *Queries) FindOneAliExpressSellerToken(ctx context.Context) (GuguAliexpressSellerToken, error) {
	row := q.db.QueryRowContext(ctx, findOneAliExpressSellerToken)
	var i GuguAliexpressSellerToken
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.HavanaID,
		&i.AppUserID,
		&i.UserNick,
		&i.Account,
		&i.AccountPlatform,
		&i.Locale,
		&i.Sp,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.LastRefreshedAt,
		&i.AuthorizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAliExpressSellerTokensExpiringBefore = `-- name: ListAliExpressSellerTokensExpiringBefore :many
SELECT
    id,
    seller_id,
    havana_id,
    app_user_id,
    user_nick,
    account,
    account_platform,
    locale,
    sp,
    access_token,
    refresh_token,
    access_token_expires_at,
    refresh_token_expires_at,
    last_refreshed_at,
    authorized_at,
    created_at,
    updated_at
FROM gugu.aliexpress_seller_token
WHERE access_token_expires_at <= $1
ORDER BY access_token_expires_at ASC
`

func (q *Queries) ListAliExpressSellerTokensExpiringBefore(ctx context.Context, accessTokenExpiresAt time.Time) ([]GuguAliexpressSellerToken, error) {
	rows, err := q.db.QueryContext(ctx, listAliExpressSellerTokensExpiringBefore, accessTokenExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguAliexpressSellerToken
	for rows.Next() {
		var i GuguAliexpressSellerToken
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.HavanaID,
			&i.AppUserID,
			&i.UserNick,
			&i.Account,
			&i.AccountPlatform,
			&i.Locale,
			&i.Sp,
			&i.AccessToken,
			&i.RefreshToken,
			&i.AccessTokenExpiresAt,
			&i.RefreshTokenExpiresAt,
			&i.LastRefreshedAt,
			&i.AuthorizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAliExpressSellerToken = `-- name: UpsertAliExpressSellerToken :exec
INSERT INTO gugu.aliexpress_seller_token (
    id,
    seller_id,
    havana_id,
    app_user_id,
    user_nick,
    account,
    account_platform,
    locale,
    sp,
    access_token,
    refresh_token,
    access_token_expires_at,
    refresh_token_expires_at,
    last_refreshed_at,
    authorized_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
ON CONFLICT (seller_id) DO UPDATE SET
    havana_id = EXCLUDED.havana_id,
    app_user_id = EXCLUDED.app_user_id,
    user_nick = EXCLUDED.user_nick,
    account = EXCLUDED.account,
    account_platform = EXCLUDED.account_platform,
    locale = EXCLUDED.locale,
    sp = EXCLUDED.sp,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    access_token_expires_at = EXCLUDED.access_token_expires_at,
    refresh_token_expires_at = EXCLUDED.refresh_token_expires_at,
    last_refreshed_at = EXCLUDED.last_refreshed_at,
    authorized_at = EXCLUDED.authorized_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertAliExpressSellerTokenParams struct {
	ID                    string       `json:"id"`
	SellerID              string       `json:"seller_id"`
	HavanaID              string       `json:"havana_id"`
	AppUserID             string       `json:"app_user_id"`
	UserNick              string       `json:"user_nick"`
	Account               string       `json:"account"`
	AccountPlatform       string       `json:"account_platform"`
	Locale                string       `json:"locale"`
	Sp                    string       `json:"sp"`
	AccessToken           string       `json:"access_token"`
	RefreshToken          string       `json:"refresh_token"`
	AccessTokenExpiresAt  time.Time    `json:"access_token_expires_at"`
	RefreshTokenExpiresAt sql.NullTime `json:"refresh_token_expires_at"`
	LastRefreshedAt       time.Time    `json:"last_refreshed_at"`
	AuthorizedAt          time.Time    `json:"authorized_at"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
}

func (q *Queries) UpsertAliExpressSellerToken(ctx context.Context, arg UpsertAliExpressSellerTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertAliExpressSellerToken,
		arg.ID,
		arg.SellerID,
		arg.HavanaID,
		arg.AppUserID,
		arg.UserNick,
		arg.Account,
		arg.AccountPlatform,
		arg.Locale,
		arg.Sp,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.LastRefreshedAt,
		arg.AuthorizedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
