// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqldb

import (
	"context"
	"database/sql"
	"time"
)

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO gugu.email_verifications (
    code,
    user_id,
    email,
    expires_at,
    used_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateEmailVerificationParams struct {
	Code      string       `json:"code"`
	UserID    string       `json:"user_id"`
	Email     string       `json:"email"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createEmailVerification,
		arg.Code,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
		arg.UsedAt,
		arg.CreatedAt,
	)
	return err
}

const createOAuthIdentity = `-- name: CreateOAuthIdentity :exec
INSERT INTO gugu.oauth_identities (
    id,
    user_id,
    provider,
    subject,
    email,
    created_at,
    last_login_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateOAuthIdentityParams struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Provider    string    `json:"provider"`
	Subject     string    `json:"subject"`
	Email       string    `json:"email"`
	CreatedAt   time.Time `json:"created_at"`
	LastLoginAt time.Time `json:"last_login_at"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
		arg.CreatedAt,
		arg.LastLoginAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO gugu.app_users (
    id,
    email,
    display_name,
    password_hash,
    auth_source,
    email_verified,
    email_verified_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateUserParams struct {
	ID              string       `json:"id"`
	Email           string       `json:"email"`
	DisplayName     string       `json:"display_name"`
	PasswordHash    string       `json:"password_hash"`
	AuthSource      string       `json:"auth_source"`
	EmailVerified   bool         `json:"email_verified"`
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
	CreatedAt       time.Time    `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.AuthSource,
		arg.EmailVerified,
		arg.EmailVerifiedAt,
		arg.CreatedAt,
	)
	return err
}

const createUserLoginSession = `-- name: CreateUserLoginSession :exec
INSERT INTO gugu.user_login_sessions (
    id,
    user_id,
    refresh_token_hash,
    token_family_id,
    parent_session_id,
    user_agent,
    client_ip,
    device_name,
    expires_at,
    last_seen_at,
    rotated_at,
    revoked_at,
    reuse_detected_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateUserLoginSessionParams struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	TokenFamilyID    string         `json:"token_family_id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	UserAgent        string         `json:"user_agent"`
	ClientIp         string         `json:"client_ip"`
	DeviceName       string         `json:"device_name"`
	ExpiresAt        time.Time      `json:"expires_at"`
	LastSeenAt       time.Time      `json:"last_seen_at"`
	RotatedAt        sql.NullTime   `json:"rotated_at"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
	ReuseDetectedAt  sql.NullTime   `json:"reuse_detected_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) CreateUserLoginSession(ctx context.Context, arg CreateUserLoginSessionParams) error {
	_, err := q.db.ExecContext(ctx, createUserLoginSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.TokenFamilyID,
		arg.ParentSessionID,
		arg.UserAgent,
		arg.ClientIp,
		arg.DeviceName,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.RotatedAt,
		arg.RevokedAt,
		arg.ReuseDetectedAt,
		arg.CreatedAt,
	)
	return err
}

const findAliExpressSellerTokenBySellerID = `-- name: FindAliExpressSellerTokenBySellerID :one
SELECT
    id,
    user_id,
    seller_id,
    havana_id,
    app_user_id,
    user_nick,
    account,
    account_platform,
    locale,
    sp,
    access_token,
    refresh_token,
    access_token_expires_at,
    refresh_token_expires_at,
    last_refreshed_at,
    authorized_at,
    created_at,
    updated_at
FROM gugu.aliexpress_seller_tokens
WHERE seller_id = $1
`

func (q *Queries) FindAliExpressSellerTokenBySellerID(ctx context.Context, sellerID string) (GuguAliexpressSellerToken, error) {
	row := q.db.QueryRowContext(ctx, findAliExpressSellerTokenBySellerID, sellerID)
	var i GuguAliexpressSellerToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SellerID,
		&i.HavanaID,
		&i.AppUserID,
		&i.UserNick,
		&i.Account,
		&i.AccountPlatform,
		&i.Locale,
		&i.Sp,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.LastRefreshedAt,
		&i.AuthorizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAliExpressSellerTokenByUserID = `-- name: FindAliExpressSellerTokenByUserID :one
SELECT
    id,
    user_id,
    seller_id,
    havana_id,
    app_user_id,
    user_nick,
    account,
    account_platform,
    locale,
    sp,
    access_token,
    refresh_token,
    access_token_expires_at,
    refresh_token_expires_at,
    last_refreshed_at,
    authorized_at,
    created_at,
    updated_at
FROM gugu.aliexpress_seller_tokens
WHERE user_id = $1
`

func (q *Queries) FindAliExpressSellerTokenByUserID(ctx context.Context, userID string) (GuguAliexpressSellerToken, error) {
	row := q.db.QueryRowContext(ctx, findAliExpressSellerTokenByUserID, userID)
	var i GuguAliexpressSellerToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SellerID,
		&i.HavanaID,
		&i.AppUserID,
		&i.UserNick,
		&i.Account,
		&i.AccountPlatform,
		&i.Locale,
		&i.Sp,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.LastRefreshedAt,
		&i.AuthorizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findEmailVerificationByCode = `-- name: FindEmailVerificationByCode :one
SELECT
    code,
    user_id,
    email,
    expires_at,
    used_at,
    created_at
FROM gugu.email_verifications
WHERE code = $1
`

func (q *Queries) FindEmailVerificationByCode(ctx context.Context, code string) (GuguEmailVerification, error) {
	row := q.db.QueryRowContext(ctx, findEmailVerificationByCode, code)
	var i GuguEmailVerification
	err := row.Scan(
		&i.Code,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findOAuthIdentity = `-- name: FindOAuthIdentity :one
SELECT
    id,
    user_id,
    provider,
    subject,
    email,
    created_at,
    last_login_at
FROM gugu.oauth_identities
WHERE provider = $1 AND subject = $2
`

type FindOAuthIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) FindOAuthIdentity(ctx context.Context, arg FindOAuthIdentityParams) (GuguOauthIdentity, error) {
	row := q.db.QueryRowContext(ctx, findOAuthIdentity, arg.Provider, arg.Subject)
	var i GuguOauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT
    id,
    email,
    display_name,
    password_hash,
    auth_source,
    email_verified,
    email_verified_at,
    created_at
FROM gugu.app_users
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (GuguAppUser, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i GuguAppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AuthSource,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT
    id,
    email,
    display_name,
    password_hash,
    auth_source,
    email_verified,
    email_verified_at,
    created_at
FROM gugu.app_users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (GuguAppUser, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i GuguAppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AuthSource,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserLoginSessionByRefreshTokenHash = `-- name: FindUserLoginSessionByRefreshTokenHash :one
SELECT
    id,
    user_id,
    refresh_token_hash,
    token_family_id,
    parent_session_id,
    user_agent,
    client_ip,
    device_name,
    expires_at,
    last_seen_at,
    rotated_at,
    revoked_at,
    reuse_detected_at,
    created_at
FROM gugu.user_login_sessions
WHERE refresh_token_hash = $1
`

func (q *Queries) FindUserLoginSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (GuguUserLoginSession, error) {
	row := q.db.QueryRowContext(ctx, findUserLoginSessionByRefreshTokenHash, refreshTokenHash)
	var i GuguUserLoginSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.TokenFamilyID,
		&i.ParentSessionID,
		&i.UserAgent,
		&i.ClientIp,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.ReuseDetectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAliExpressSellerTokensExpiringBefore = `-- name: ListAliExpressSellerTokensExpiringBefore :many
SELECT
    id,
    user_id,
    seller_id,
    havana_id,
    app_user_id,
    user_nick,
    account,
    account_platform,
    locale,
    sp,
    access_token,
    refresh_token,
    access_token_expires_at,
    refresh_token_expires_at,
    last_refreshed_at,
    authorized_at,
    created_at,
    updated_at
FROM gugu.aliexpress_seller_tokens
WHERE access_token_expires_at <= $1
ORDER BY access_token_expires_at ASC
`

func (q *Queries) ListAliExpressSellerTokensExpiringBefore(ctx context.Context, accessTokenExpiresAt time.Time) ([]GuguAliexpressSellerToken, error) {
	rows, err := q.db.QueryContext(ctx, listAliExpressSellerTokensExpiringBefore, accessTokenExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguAliexpressSellerToken
	for rows.Next() {
		var i GuguAliexpressSellerToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SellerID,
			&i.HavanaID,
			&i.AppUserID,
			&i.UserNick,
			&i.Account,
			&i.AccountPlatform,
			&i.Locale,
			&i.Sp,
			&i.AccessToken,
			&i.RefreshToken,
			&i.AccessTokenExpiresAt,
			&i.RefreshTokenExpiresAt,
			&i.LastRefreshedAt,
			&i.AuthorizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :execrows
UPDATE gugu.email_verifications
SET used_at = $2
WHERE code = $1
`

type MarkEmailVerificationUsedParams struct {
	Code   string       `json:"code"`
	UsedAt sql.NullTime `json:"used_at"`
}

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, arg MarkEmailVerificationUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markEmailVerificationUsed, arg.Code, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :execrows
UPDATE gugu.app_users
SET
    email_verified = TRUE,
    email_verified_at = $2
WHERE id = $1
`

type MarkUserEmailVerifiedParams struct {
	ID              string       `json:"id"`
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUserEmailVerified, arg.ID, arg.EmailVerifiedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markUserLoginSessionReuseDetected = `-- name: MarkUserLoginSessionReuseDetected :execrows
UPDATE gugu.user_login_sessions
SET reuse_detected_at = $2
WHERE id = $1
`

type MarkUserLoginSessionReuseDetectedParams struct {
	ID              string       `json:"id"`
	ReuseDetectedAt sql.NullTime `json:"reuse_detected_at"`
}

func (q *Queries) MarkUserLoginSessionReuseDetected(ctx context.Context, arg MarkUserLoginSessionReuseDetectedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUserLoginSessionReuseDetected, arg.ID, arg.ReuseDetectedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markUserLoginSessionRotated = `-- name: MarkUserLoginSessionRotated :execrows
UPDATE gugu.user_login_sessions
SET rotated_at = $2
WHERE id = $1
`

type MarkUserLoginSessionRotatedParams struct {
	ID        string       `json:"id"`
	RotatedAt sql.NullTime `json:"rotated_at"`
}

func (q *Queries) MarkUserLoginSessionRotated(ctx context.Context, arg MarkUserLoginSessionRotatedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUserLoginSessionRotated, arg.ID, arg.RotatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserLoginSession = `-- name: RevokeUserLoginSession :execrows
UPDATE gugu.user_login_sessions
SET revoked_at = $2
WHERE id = $1
`

type RevokeUserLoginSessionParams struct {
	ID        string       `json:"id"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) RevokeUserLoginSession(ctx context.Context, arg RevokeUserLoginSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUserLoginSession, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserLoginSessionFamily = `-- name: RevokeUserLoginSessionFamily :execrows
UPDATE gugu.user_login_sessions
SET revoked_at = $2
WHERE token_family_id = $1
`

type RevokeUserLoginSessionFamilyParams struct {
	TokenFamilyID string       `json:"token_family_id"`
	RevokedAt     sql.NullTime `json:"revoked_at"`
}

func (q *Queries) RevokeUserLoginSessionFamily(ctx context.Context, arg RevokeUserLoginSessionFamilyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUserLoginSessionFamily, arg.TokenFamilyID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateOAuthLastLogin = `-- name: UpdateOAuthLastLogin :execrows
UPDATE gugu.oauth_identities
SET last_login_at = $3
WHERE provider = $1 AND subject = $2
`

type UpdateOAuthLastLoginParams struct {
	Provider    string    `json:"provider"`
	Subject     string    `json:"subject"`
	LastLoginAt time.Time `json:"last_login_at"`
}

func (q *Queries) UpdateOAuthLastLogin(ctx context.Context, arg UpdateOAuthLastLoginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOAuthLastLogin, arg.Provider, arg.Subject, arg.LastLoginAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserLoginSessionLastSeen = `-- name: UpdateUserLoginSessionLastSeen :execrows
UPDATE gugu.user_login_sessions
SET last_seen_at = $2
WHERE id = $1
`

type UpdateUserLoginSessionLastSeenParams struct {
	ID         string    `json:"id"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

func (q *Queries) UpdateUserLoginSessionLastSeen(ctx context.Context, arg UpdateUserLoginSessionLastSeenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserLoginSessionLastSeen, arg.ID, arg.LastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAliExpressSellerToken = `-- name: UpsertAliExpressSellerToken :exec
INSERT INTO gugu.aliexpress_seller_tokens (
    id,
    user_id,
    seller_id,
    havana_id,
    app_user_id,
    user_nick,
    account,
    account_platform,
    locale,
    sp,
    access_token,
    refresh_token,
    access_token_expires_at,
    refresh_token_expires_at,
    last_refreshed_at,
    authorized_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
ON CONFLICT (seller_id) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    havana_id = EXCLUDED.havana_id,
    app_user_id = EXCLUDED.app_user_id,
    user_nick = EXCLUDED.user_nick,
    account = EXCLUDED.account,
    account_platform = EXCLUDED.account_platform,
    locale = EXCLUDED.locale,
    sp = EXCLUDED.sp,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    access_token_expires_at = EXCLUDED.access_token_expires_at,
    refresh_token_expires_at = EXCLUDED.refresh_token_expires_at,
    last_refreshed_at = EXCLUDED.last_refreshed_at,
    authorized_at = EXCLUDED.authorized_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertAliExpressSellerTokenParams struct {
	ID                    string       `json:"id"`
	UserID                string       `json:"user_id"`
	SellerID              string       `json:"seller_id"`
	HavanaID              string       `json:"havana_id"`
	AppUserID             string       `json:"app_user_id"`
	UserNick              string       `json:"user_nick"`
	Account               string       `json:"account"`
	AccountPlatform       string       `json:"account_platform"`
	Locale                string       `json:"locale"`
	Sp                    string       `json:"sp"`
	AccessToken           string       `json:"access_token"`
	RefreshToken          string       `json:"refresh_token"`
	AccessTokenExpiresAt  time.Time    `json:"access_token_expires_at"`
	RefreshTokenExpiresAt sql.NullTime `json:"refresh_token_expires_at"`
	LastRefreshedAt       time.Time    `json:"last_refreshed_at"`
	AuthorizedAt          time.Time    `json:"authorized_at"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
}

func (q *Queries) UpsertAliExpressSellerToken(ctx context.Context, arg UpsertAliExpressSellerTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertAliExpressSellerToken,
		arg.ID,
		arg.UserID,
		arg.SellerID,
		arg.HavanaID,
		arg.AppUserID,
		arg.UserNick,
		arg.Account,
		arg.AccountPlatform,
		arg.Locale,
		arg.Sp,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.LastRefreshedAt,
		arg.AuthorizedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
