// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification.sql

package sqldb

import (
	"context"
	"database/sql"
	"time"
)

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO gugu.email_verifications (
    code,
    user_id,
    email,
    expires_at,
    used_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateEmailVerificationParams struct {
	Code      string       `json:"code"`
	UserID    string       `json:"user_id"`
	Email     string       `json:"email"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createEmailVerification,
		arg.Code,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
		arg.UsedAt,
		arg.CreatedAt,
	)
	return err
}

const findEmailVerificationByCode = `-- name: FindEmailVerificationByCode :one
SELECT
    code,
    user_id,
    email,
    expires_at,
    used_at,
    created_at
FROM gugu.email_verifications
WHERE code = $1
`

func (q *Queries) FindEmailVerificationByCode(ctx context.Context, code string) (GuguEmailVerification, error) {
	row := q.db.QueryRowContext(ctx, findEmailVerificationByCode, code)
	var i GuguEmailVerification
	err := row.Scan(
		&i.Code,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :execrows
UPDATE gugu.email_verifications
SET used_at = $2
WHERE code = $1
`

type MarkEmailVerificationUsedParams struct {
	Code   string       `json:"code"`
	UsedAt sql.NullTime `json:"used_at"`
}

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, arg MarkEmailVerificationUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markEmailVerificationUsed, arg.Code, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
