// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_session.sql

package sqldb

import (
	"context"
	"database/sql"
	"time"
)

const createUserLoginSession = `-- name: CreateUserLoginSession :exec
INSERT INTO gugu.user_login_session (
    id,
    user_id,
    refresh_token_hash,
    token_family_id,
    parent_session_id,
    user_agent,
    client_ip,
    device_name,
    expires_at,
    last_seen_at,
    rotated_at,
    revoked_at,
    reuse_detected_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateUserLoginSessionParams struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	TokenFamilyID    string         `json:"token_family_id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	UserAgent        string         `json:"user_agent"`
	ClientIp         string         `json:"client_ip"`
	DeviceName       string         `json:"device_name"`
	ExpiresAt        time.Time      `json:"expires_at"`
	LastSeenAt       time.Time      `json:"last_seen_at"`
	RotatedAt        sql.NullTime   `json:"rotated_at"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
	ReuseDetectedAt  sql.NullTime   `json:"reuse_detected_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) CreateUserLoginSession(ctx context.Context, arg CreateUserLoginSessionParams) error {
	_, err := q.db.ExecContext(ctx, createUserLoginSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.TokenFamilyID,
		arg.ParentSessionID,
		arg.UserAgent,
		arg.ClientIp,
		arg.DeviceName,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.RotatedAt,
		arg.RevokedAt,
		arg.ReuseDetectedAt,
		arg.CreatedAt,
	)
	return err
}

const findUserLoginSessionByRefreshTokenHash = `-- name: FindUserLoginSessionByRefreshTokenHash :one
SELECT
    id,
    user_id,
    refresh_token_hash,
    token_family_id,
    parent_session_id,
    user_agent,
    client_ip,
    device_name,
    expires_at,
    last_seen_at,
    rotated_at,
    revoked_at,
    reuse_detected_at,
    created_at
FROM gugu.user_login_session
WHERE refresh_token_hash = $1
`

func (q *Queries) FindUserLoginSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (GuguUserLoginSession, error) {
	row := q.db.QueryRowContext(ctx, findUserLoginSessionByRefreshTokenHash, refreshTokenHash)
	var i GuguUserLoginSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.TokenFamilyID,
		&i.ParentSessionID,
		&i.UserAgent,
		&i.ClientIp,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.ReuseDetectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countActiveUserLoginSessionsByUserID = `-- name: CountActiveUserLoginSessionsByUserID :one
SELECT COUNT(*)
FROM gugu.user_login_session
WHERE user_id = $1
  AND revoked_at IS NULL
  AND rotated_at IS NULL
  AND expires_at > $2
`

type CountActiveUserLoginSessionsByUserIDParams struct {
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CountActiveUserLoginSessionsByUserID(ctx context.Context, arg CountActiveUserLoginSessionsByUserIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUserLoginSessionsByUserID, arg.UserID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActiveUserLoginSessionsByUserID = `-- name: ListActiveUserLoginSessionsByUserID :many
SELECT
    id,
    user_id,
    refresh_token_hash,
    token_family_id,
    parent_session_id,
    user_agent,
    client_ip,
    device_name,
    expires_at,
    last_seen_at,
    rotated_at,
    revoked_at,
    reuse_detected_at,
    created_at
FROM gugu.user_login_session
WHERE user_id = $1
  AND revoked_at IS NULL
  AND rotated_at IS NULL
  AND expires_at > $2
ORDER BY created_at DESC
`

func (q *Queries) ListActiveUserLoginSessionsByUserID(ctx context.Context, arg CountActiveUserLoginSessionsByUserIDParams) ([]GuguUserLoginSession, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUserLoginSessionsByUserID, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuguUserLoginSession{}
	for rows.Next() {
		var i GuguUserLoginSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.TokenFamilyID,
			&i.ParentSessionID,
			&i.UserAgent,
			&i.ClientIp,
			&i.DeviceName,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.RotatedAt,
			&i.RevokedAt,
			&i.ReuseDetectedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserLoginSessionByUserIDSessionID = `-- name: RevokeUserLoginSessionByUserIDSessionID :exec
UPDATE gugu.user_login_session
SET revoked_at = $3
WHERE user_id = $1
  AND id = $2
  AND revoked_at IS NULL
`

type RevokeUserLoginSessionByUserIDSessionIDParams struct {
	UserID    string       `json:"user_id"`
	ID        string       `json:"id"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) RevokeUserLoginSessionByUserIDSessionID(ctx context.Context, arg RevokeUserLoginSessionByUserIDSessionIDParams) error {
	_, err := q.db.ExecContext(ctx, revokeUserLoginSessionByUserIDSessionID, arg.UserID, arg.ID, arg.RevokedAt)
	return err
}

const revokeOldestActiveUserLoginSessionByUserID = `-- name: RevokeOldestActiveUserLoginSessionByUserID :execrows
UPDATE gugu.user_login_session
SET revoked_at = $2
WHERE id = (
    SELECT id
    FROM gugu.user_login_session
    WHERE user_id = $1
      AND revoked_at IS NULL
      AND rotated_at IS NULL
      AND expires_at > $3
    ORDER BY created_at ASC
    LIMIT 1
)
`

type RevokeOldestActiveUserLoginSessionByUserIDParams struct {
	UserID    string       `json:"user_id"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	ExpiresAt time.Time    `json:"expires_at"`
}

func (q *Queries) RevokeOldestActiveUserLoginSessionByUserID(ctx context.Context, arg RevokeOldestActiveUserLoginSessionByUserIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeOldestActiveUserLoginSessionByUserID, arg.UserID, arg.RevokedAt, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markUserLoginSessionReuseDetected = `-- name: MarkUserLoginSessionReuseDetected :execrows
UPDATE gugu.user_login_session
SET reuse_detected_at = $2
WHERE id = $1
`

type MarkUserLoginSessionReuseDetectedParams struct {
	ID              string       `json:"id"`
	ReuseDetectedAt sql.NullTime `json:"reuse_detected_at"`
}

func (q *Queries) MarkUserLoginSessionReuseDetected(ctx context.Context, arg MarkUserLoginSessionReuseDetectedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUserLoginSessionReuseDetected, arg.ID, arg.ReuseDetectedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markUserLoginSessionRotated = `-- name: MarkUserLoginSessionRotated :execrows
UPDATE gugu.user_login_session
SET rotated_at = $2
WHERE id = $1
`

type MarkUserLoginSessionRotatedParams struct {
	ID        string       `json:"id"`
	RotatedAt sql.NullTime `json:"rotated_at"`
}

func (q *Queries) MarkUserLoginSessionRotated(ctx context.Context, arg MarkUserLoginSessionRotatedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUserLoginSessionRotated, arg.ID, arg.RotatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserLoginSession = `-- name: RevokeUserLoginSession :execrows
UPDATE gugu.user_login_session
SET revoked_at = $2
WHERE id = $1
`

type RevokeUserLoginSessionParams struct {
	ID        string       `json:"id"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) RevokeUserLoginSession(ctx context.Context, arg RevokeUserLoginSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUserLoginSession, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserLoginSessionFamily = `-- name: RevokeUserLoginSessionFamily :execrows
UPDATE gugu.user_login_session
SET revoked_at = $2
WHERE token_family_id = $1
`

type RevokeUserLoginSessionFamilyParams struct {
	TokenFamilyID string       `json:"token_family_id"`
	RevokedAt     sql.NullTime `json:"revoked_at"`
}

func (q *Queries) RevokeUserLoginSessionFamily(ctx context.Context, arg RevokeUserLoginSessionFamilyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUserLoginSessionFamily, arg.TokenFamilyID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserLoginSessionLastSeen = `-- name: UpdateUserLoginSessionLastSeen :execrows
UPDATE gugu.user_login_session
SET last_seen_at = $2
WHERE id = $1
`

type UpdateUserLoginSessionLastSeenParams struct {
	ID         string    `json:"id"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

func (q *Queries) UpdateUserLoginSessionLastSeen(ctx context.Context, arg UpdateUserLoginSessionLastSeenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserLoginSessionLastSeen, arg.ID, arg.LastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
