// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqldb

import (
	"database/sql"
	"time"
)

type GuguAliexpressSellerToken struct {
	ID                    string       `json:"id"`
	UserID                string       `json:"user_id"`
	SellerID              string       `json:"seller_id"`
	HavanaID              string       `json:"havana_id"`
	AppUserID             string       `json:"app_user_id"`
	UserNick              string       `json:"user_nick"`
	Account               string       `json:"account"`
	AccountPlatform       string       `json:"account_platform"`
	Locale                string       `json:"locale"`
	Sp                    string       `json:"sp"`
	AccessToken           string       `json:"access_token"`
	RefreshToken          string       `json:"refresh_token"`
	AccessTokenExpiresAt  time.Time    `json:"access_token_expires_at"`
	RefreshTokenExpiresAt sql.NullTime `json:"refresh_token_expires_at"`
	LastRefreshedAt       time.Time    `json:"last_refreshed_at"`
	AuthorizedAt          time.Time    `json:"authorized_at"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
}

type GuguAppUser struct {
	ID              string       `json:"id"`
	Email           string       `json:"email"`
	DisplayName     string       `json:"display_name"`
	PasswordHash    string       `json:"password_hash"`
	AuthSource      string       `json:"auth_source"`
	EmailVerified   bool         `json:"email_verified"`
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
	CreatedAt       time.Time    `json:"created_at"`
}

type GuguEmailVerification struct {
	Code      string       `json:"code"`
	UserID    string       `json:"user_id"`
	Email     string       `json:"email"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type GuguOauthIdentity struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Provider    string    `json:"provider"`
	Subject     string    `json:"subject"`
	Email       string    `json:"email"`
	CreatedAt   time.Time `json:"created_at"`
	LastLoginAt time.Time `json:"last_login_at"`
}

type GuguProduct struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	CurrentPrice      string    `json:"current_price"`
	Currency          string    `json:"currency"`
	ProductUrl        string    `json:"product_url"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type GuguProductPriceHistory struct {
	ProductID   string    `json:"product_id"`
	RecordedAt  time.Time `json:"recorded_at"`
	Price       string    `json:"price"`
	Currency    string    `json:"currency"`
	ChangeValue string    `json:"change_value"`
}

type GuguUserLoginSession struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	TokenFamilyID    string         `json:"token_family_id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	UserAgent        string         `json:"user_agent"`
	ClientIp         string         `json:"client_ip"`
	DeviceName       string         `json:"device_name"`
	ExpiresAt        time.Time      `json:"expires_at"`
	LastSeenAt       time.Time      `json:"last_seen_at"`
	RotatedAt        sql.NullTime   `json:"rotated_at"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
	ReuseDetectedAt  sql.NullTime   `json:"reuse_detected_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

type GuguUserTrackedItem struct {
	ID          string       `json:"id"`
	UserID      string       `json:"user_id"`
	ProductID   string       `json:"product_id"`
	OriginalUrl string       `json:"original_url"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	CreatedAt   time.Time    `json:"created_at"`
}
