// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqldb

import (
	"database/sql"
	"time"
)

type GuguAliexpressSellerToken struct {
	ID                    string       `json:"id"`
	AppType               string       `json:"app_type"`
	SellerID              string       `json:"seller_id"`
	HavanaID              string       `json:"havana_id"`
	AppUserID             string       `json:"app_user_id"`
	UserNick              string       `json:"user_nick"`
	Account               string       `json:"account"`
	AccountPlatform       string       `json:"account_platform"`
	Locale                string       `json:"locale"`
	Sp                    string       `json:"sp"`
	AccessToken           string       `json:"access_token"`
	RefreshToken          string       `json:"refresh_token"`
	AccessTokenExpiresAt  time.Time    `json:"access_token_expires_at"`
	RefreshTokenExpiresAt sql.NullTime `json:"refresh_token_expires_at"`
	LastRefreshedAt       time.Time    `json:"last_refreshed_at"`
	AuthorizedAt          time.Time    `json:"authorized_at"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
}

type GuguAppUser struct {
	ID              string       `json:"id"`
	Email           string       `json:"email"`
	DisplayName     string       `json:"display_name"`
	PasswordHash    string       `json:"password_hash"`
	AuthSource      string       `json:"auth_source"`
	EmailVerified   bool         `json:"email_verified"`
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
	CreatedAt       time.Time    `json:"created_at"`
}

type GuguEmailVerification struct {
	Code      string       `json:"code"`
	UserID    string       `json:"user_id"`
	Email     string       `json:"email"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type GuguOauthIdentity struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Provider    string    `json:"provider"`
	Subject     string    `json:"subject"`
	Email       string    `json:"email"`
	CreatedAt   time.Time `json:"created_at"`
	LastLoginAt time.Time `json:"last_login_at"`
}

type GuguPriceAlert struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	SkuID     string    `json:"sku_id"`
	Channel   string    `json:"channel"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
}

type GuguProduct struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	ProductUrl        string    `json:"product_url"`
	PromotionLink     string    `json:"promotion_link"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type GuguSku struct {
	ID            string    `json:"id"`
	ProductID     string    `json:"product_id"`
	ExternalSkuID string    `json:"external_sku_id"`
	OriginSkuID   string    `json:"origin_sku_id"`
	SkuName       string    `json:"sku_name"`
	Color         string    `json:"color"`
	Size          string    `json:"size"`
	Price         string    `json:"price"`
	OriginalPrice string    `json:"original_price"`
	Currency      string    `json:"currency"`
	ImageUrl      string    `json:"image_url"`
	SkuProperties string    `json:"sku_properties"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type GuguSkuPriceHistory struct {
	SkuID       string    `json:"sku_id"`
	RecordedAt  time.Time `json:"recorded_at"`
	Price       string    `json:"price"`
	Currency    string    `json:"currency"`
	ChangeValue string    `json:"change_value"`
}

type GuguSkuPriceSnapshot struct {
	SkuID         string    `json:"sku_id"`
	SnapshotDate  time.Time `json:"snapshot_date"`
	Price         string    `json:"price"`
	OriginalPrice string    `json:"original_price"`
	Currency      string    `json:"currency"`
}

type GuguUserLoginSession struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	TokenFamilyID    string         `json:"token_family_id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	UserAgent        string         `json:"user_agent"`
	ClientIp         string         `json:"client_ip"`
	DeviceName       string         `json:"device_name"`
	ExpiresAt        time.Time      `json:"expires_at"`
	LastSeenAt       time.Time      `json:"last_seen_at"`
	RotatedAt        sql.NullTime   `json:"rotated_at"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
	ReuseDetectedAt  sql.NullTime   `json:"reuse_detected_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

type GuguUserTrackedItem struct {
	ID                    string         `json:"id"`
	UserID                string         `json:"user_id"`
	ProductID             string         `json:"product_id"`
	SkuID                 sql.NullString `json:"sku_id"`
	OriginalUrl           string         `json:"original_url"`
	ViewExternalProductID string         `json:"view_external_product_id"`
	PreferredLanguage     string         `json:"preferred_language"`
	TrackingScope         string         `json:"tracking_scope"`
	Currency              string         `json:"currency"`
	DeletedAt             sql.NullTime   `json:"deleted_at"`
	CreatedAt             time.Time      `json:"created_at"`
}

type GuguUserTrackedItemWatchSku struct {
	TrackedItemID string    `json:"tracked_item_id"`
	SkuID         string    `json:"sku_id"`
	CreatedAt     time.Time `json:"created_at"`
}
