// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_identity.sql

package sqldb

import (
	"context"
	"time"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :exec
INSERT INTO gugu.oauth_identities (
    id,
    user_id,
    provider,
    subject,
    email,
    created_at,
    last_login_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateOAuthIdentityParams struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Provider    string    `json:"provider"`
	Subject     string    `json:"subject"`
	Email       string    `json:"email"`
	CreatedAt   time.Time `json:"created_at"`
	LastLoginAt time.Time `json:"last_login_at"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
		arg.CreatedAt,
		arg.LastLoginAt,
	)
	return err
}

const findOAuthIdentity = `-- name: FindOAuthIdentity :one
SELECT
    id,
    user_id,
    provider,
    subject,
    email,
    created_at,
    last_login_at
FROM gugu.oauth_identities
WHERE provider = $1 AND subject = $2
`

type FindOAuthIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) FindOAuthIdentity(ctx context.Context, arg FindOAuthIdentityParams) (GuguOauthIdentity, error) {
	row := q.db.QueryRowContext(ctx, findOAuthIdentity, arg.Provider, arg.Subject)
	var i GuguOauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateOAuthLastLogin = `-- name: UpdateOAuthLastLogin :execrows
UPDATE gugu.oauth_identities
SET last_login_at = $3
WHERE provider = $1 AND subject = $2
`

type UpdateOAuthLastLoginParams struct {
	Provider    string    `json:"provider"`
	Subject     string    `json:"subject"`
	LastLoginAt time.Time `json:"last_login_at"`
}

func (q *Queries) UpdateOAuthLastLogin(ctx context.Context, arg UpdateOAuthLastLoginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOAuthLastLogin, arg.Provider, arg.Subject, arg.LastLoginAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
