// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_alert.sql

package sqldb

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createPriceAlert = `-- name: CreatePriceAlert :exec
INSERT INTO gugu.price_alert (
    id, user_id, product_id, channel, enabled, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreatePriceAlertParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	ProductID string    `json:"product_id"`
	Channel   string    `json:"channel"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreatePriceAlert(ctx context.Context, arg CreatePriceAlertParams) error {
	_, err := q.db.ExecContext(ctx, createPriceAlert,
		arg.ID,
		arg.UserID,
		arg.ProductID,
		arg.Channel,
		arg.Enabled,
		arg.CreatedAt,
	)
	return err
}

const deletePriceAlertByUserIDAndProductID = `-- name: DeletePriceAlertByUserIDAndProductID :execrows
DELETE FROM gugu.price_alert
WHERE user_id = $1 AND product_id = $2
`

type DeletePriceAlertByUserIDAndProductIDParams struct {
	UserID    string `json:"user_id"`
	ProductID string `json:"product_id"`
}

func (q *Queries) DeletePriceAlertByUserIDAndProductID(ctx context.Context, arg DeletePriceAlertByUserIDAndProductIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePriceAlertByUserIDAndProductID, arg.UserID, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findPriceAlertByUserIDAndProductID = `-- name: FindPriceAlertByUserIDAndProductID :one
SELECT id, user_id, product_id, channel, enabled, created_at
FROM gugu.price_alert
WHERE user_id = $1 AND product_id = $2
`

type FindPriceAlertByUserIDAndProductIDParams struct {
	UserID    string `json:"user_id"`
	ProductID string `json:"product_id"`
}

func (q *Queries) FindPriceAlertByUserIDAndProductID(ctx context.Context, arg FindPriceAlertByUserIDAndProductIDParams) (GuguPriceAlert, error) {
	row := q.db.QueryRowContext(ctx, findPriceAlertByUserIDAndProductID, arg.UserID, arg.ProductID)
	var i GuguPriceAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Channel,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listPriceAlertsByProductID = `-- name: ListPriceAlertsByProductID :many
SELECT id, user_id, product_id, channel, enabled, created_at
FROM gugu.price_alert
WHERE product_id = $1 AND enabled = TRUE
`

func (q *Queries) ListPriceAlertsByProductID(ctx context.Context, productID string) ([]GuguPriceAlert, error) {
	rows, err := q.db.QueryContext(ctx, listPriceAlertsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguPriceAlert
	for rows.Next() {
		var i GuguPriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Channel,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceAlertsByProductIDs = `-- name: ListPriceAlertsByProductIDs :many
SELECT id, user_id, product_id, channel, enabled, created_at
FROM gugu.price_alert
WHERE product_id = ANY($1::text[]) AND enabled = TRUE
`

func (q *Queries) ListPriceAlertsByProductIDs(ctx context.Context, dollar_1 []string) ([]GuguPriceAlert, error) {
	rows, err := q.db.QueryContext(ctx, listPriceAlertsByProductIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguPriceAlert
	for rows.Next() {
		var i GuguPriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Channel,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceAlertsByUserID = `-- name: ListPriceAlertsByUserID :many
SELECT id, user_id, product_id, channel, enabled, created_at
FROM gugu.price_alert
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPriceAlertsByUserID(ctx context.Context, userID string) ([]GuguPriceAlert, error) {
	rows, err := q.db.QueryContext(ctx, listPriceAlertsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguPriceAlert
	for rows.Next() {
		var i GuguPriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Channel,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceAlertEnabled = `-- name: UpdatePriceAlertEnabled :execrows
UPDATE gugu.price_alert
SET enabled = $2
WHERE id = $1
`

type UpdatePriceAlertEnabledParams struct {
	ID      string `json:"id"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) UpdatePriceAlertEnabled(ctx context.Context, arg UpdatePriceAlertEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePriceAlertEnabled, arg.ID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
