// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_history.sql

package sqldb

import (
	"context"
	"time"
)

const createPriceHistory = `-- name: CreatePriceHistory :exec
INSERT INTO gugu.product_price_history (
    product_id,
    price,
    currency,
    recorded_at,
    change_value
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreatePriceHistoryParams struct {
	ProductID   string    `json:"product_id"`
	Price       string    `json:"price"`
	Currency    string    `json:"currency"`
	RecordedAt  time.Time `json:"recorded_at"`
	ChangeValue string    `json:"change_value"`
}

func (q *Queries) CreatePriceHistory(ctx context.Context, arg CreatePriceHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createPriceHistory,
		arg.ProductID,
		arg.Price,
		arg.Currency,
		arg.RecordedAt,
		arg.ChangeValue,
	)
	return err
}

const listPriceHistoriesByProductID = `-- name: ListPriceHistoriesByProductID :many
SELECT
    product_id,
    price,
    currency,
    recorded_at,
    change_value
FROM gugu.product_price_history
WHERE product_id = $1
ORDER BY recorded_at DESC
`

type ListPriceHistoriesByProductIDRow struct {
	ProductID   string    `json:"product_id"`
	Price       string    `json:"price"`
	Currency    string    `json:"currency"`
	RecordedAt  time.Time `json:"recorded_at"`
	ChangeValue string    `json:"change_value"`
}

func (q *Queries) ListPriceHistoriesByProductID(ctx context.Context, productID string) ([]ListPriceHistoriesByProductIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPriceHistoriesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPriceHistoriesByProductIDRow
	for rows.Next() {
		var i ListPriceHistoriesByProductIDRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Price,
			&i.Currency,
			&i.RecordedAt,
			&i.ChangeValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
