// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_alert.sql

package sqldb

import (
	"context"
	"time"
)

const createPriceAlert = `-- name: CreatePriceAlert :exec
INSERT INTO gugu.price_alert (
    id, user_id, sku_id, channel, enabled, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreatePriceAlertParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	SkuID     string    `json:"sku_id"`
	Channel   string    `json:"channel"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreatePriceAlert(ctx context.Context, arg CreatePriceAlertParams) error {
	_, err := q.db.ExecContext(ctx, createPriceAlert,
		arg.ID,
		arg.UserID,
		arg.SkuID,
		arg.Channel,
		arg.Enabled,
		arg.CreatedAt,
	)
	return err
}

const findPriceAlertByUserIDAndSKUID = `-- name: FindPriceAlertByUserIDAndSKUID :one
SELECT id, user_id, sku_id, channel, enabled, created_at
FROM gugu.price_alert
WHERE user_id = $1 AND sku_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type FindPriceAlertByUserIDAndSKUIDParams struct {
	UserID string `json:"user_id"`
	SkuID  string `json:"sku_id"`
}

func (q *Queries) FindPriceAlertByUserIDAndSKUID(ctx context.Context, arg FindPriceAlertByUserIDAndSKUIDParams) (GuguPriceAlert, error) {
	row := q.db.QueryRowContext(ctx, findPriceAlertByUserIDAndSKUID, arg.UserID, arg.SkuID)
	var i GuguPriceAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkuID,
		&i.Channel,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listPriceAlertsBySKUID = `-- name: ListPriceAlertsBySKUID :many
SELECT id, user_id, sku_id, channel, enabled, created_at
FROM gugu.price_alert
WHERE sku_id = $1 AND enabled = TRUE
`

func (q *Queries) ListPriceAlertsBySKUID(ctx context.Context, skuID string) ([]GuguPriceAlert, error) {
	rows, err := q.db.QueryContext(ctx, listPriceAlertsBySKUID, skuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguPriceAlert
	for rows.Next() {
		var i GuguPriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SkuID,
			&i.Channel,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceAlertsByUserID = `-- name: ListPriceAlertsByUserID :many
SELECT id, user_id, sku_id, channel, enabled, created_at
FROM gugu.price_alert
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPriceAlertsByUserID(ctx context.Context, userID string) ([]GuguPriceAlert, error) {
	rows, err := q.db.QueryContext(ctx, listPriceAlertsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguPriceAlert
	for rows.Next() {
		var i GuguPriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SkuID,
			&i.Channel,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceAlertEnabled = `-- name: UpdatePriceAlertEnabled :execrows
UPDATE gugu.price_alert
SET enabled = $2
WHERE id = $1
`

type UpdatePriceAlertEnabledParams struct {
	ID      string `json:"id"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) UpdatePriceAlertEnabled(ctx context.Context, arg UpdatePriceAlertEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePriceAlertEnabled, arg.ID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePriceAlertSettings = `-- name: UpdatePriceAlertSettings :execrows
UPDATE gugu.price_alert
SET channel = $2,
    enabled = $3
WHERE id = $1
`

type UpdatePriceAlertSettingsParams struct {
	ID      string `json:"id"`
	Channel string `json:"channel"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) UpdatePriceAlertSettings(ctx context.Context, arg UpdatePriceAlertSettingsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePriceAlertSettings, arg.ID, arg.Channel, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
