// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_price_snapshot.sql

package sqldb

import (
	"context"
	"time"
)

const listProductPriceSnapshotsByDateRange = `-- name: ListProductPriceSnapshotsByDateRange :many
SELECT
    product_id,
    snapshot_date,
    price,
    currency
FROM gugu.product_price_snapshot
WHERE product_id = $1
  AND snapshot_date >= $2
  AND snapshot_date <= $3
ORDER BY snapshot_date ASC
`

type ListProductPriceSnapshotsByDateRangeParams struct {
	ProductID      string    `json:"product_id"`
	SnapshotDate   time.Time `json:"snapshot_date"`
	SnapshotDate_2 time.Time `json:"snapshot_date_2"`
}

func (q *Queries) ListProductPriceSnapshotsByDateRange(ctx context.Context, arg ListProductPriceSnapshotsByDateRangeParams) ([]GuguProductPriceSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listProductPriceSnapshotsByDateRange, arg.ProductID, arg.SnapshotDate, arg.SnapshotDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguProductPriceSnapshot
	for rows.Next() {
		var i GuguProductPriceSnapshot
		if err := rows.Scan(
			&i.ProductID,
			&i.SnapshotDate,
			&i.Price,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProductPriceSnapshot = `-- name: UpsertProductPriceSnapshot :exec
INSERT INTO gugu.product_price_snapshot (
    product_id,
    snapshot_date,
    price,
    currency
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (product_id, snapshot_date) DO UPDATE SET
    price = EXCLUDED.price,
    currency = EXCLUDED.currency
`

type UpsertProductPriceSnapshotParams struct {
	ProductID    string    `json:"product_id"`
	SnapshotDate time.Time `json:"snapshot_date"`
	Price        string    `json:"price"`
	Currency     string    `json:"currency"`
}

func (q *Queries) UpsertProductPriceSnapshot(ctx context.Context, arg UpsertProductPriceSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertProductPriceSnapshot,
		arg.ProductID,
		arg.SnapshotDate,
		arg.Price,
		arg.Currency,
	)
	return err
}
