// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package sqldb

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createProduct = `-- name: CreateProduct :exec
INSERT INTO gugu.product (
    id,
    market,
    external_product_id,
    original_url,
    title,
    main_image_url,
    current_price,
    currency,
    product_url,
    promotion_link,
    collection_source,
    last_collected_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateProductParams struct {
	ID                string    `json:"id"`
	Market            string    `json:"market"`
	ExternalProductID string    `json:"external_product_id"`
	OriginalUrl       string    `json:"original_url"`
	Title             string    `json:"title"`
	MainImageUrl      string    `json:"main_image_url"`
	CurrentPrice      string    `json:"current_price"`
	Currency          string    `json:"currency"`
	ProductUrl        string    `json:"product_url"`
	PromotionLink     string    `json:"promotion_link"`
	CollectionSource  string    `json:"collection_source"`
	LastCollectedAt   time.Time `json:"last_collected_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.Market,
		arg.ExternalProductID,
		arg.OriginalUrl,
		arg.Title,
		arg.MainImageUrl,
		arg.CurrentPrice,
		arg.Currency,
		arg.ProductUrl,
		arg.PromotionLink,
		arg.CollectionSource,
		arg.LastCollectedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findProductByID = `-- name: FindProductByID :one
SELECT
    id,
    market,
    external_product_id,
    original_url,
    title,
    main_image_url,
    current_price,
    currency,
    product_url,
    promotion_link,
    collection_source,
    last_collected_at,
    created_at,
    updated_at
FROM gugu.product
WHERE id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id string) (GuguProduct, error) {
	row := q.db.QueryRowContext(ctx, findProductByID, id)
	var i GuguProduct
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.ExternalProductID,
		&i.OriginalUrl,
		&i.Title,
		&i.MainImageUrl,
		&i.CurrentPrice,
		&i.Currency,
		&i.ProductUrl,
		&i.PromotionLink,
		&i.CollectionSource,
		&i.LastCollectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProductByMarketAndExternalProductID = `-- name: FindProductByMarketAndExternalProductID :one
SELECT
    id,
    market,
    external_product_id,
    original_url,
    title,
    main_image_url,
    current_price,
    currency,
    product_url,
    promotion_link,
    collection_source,
    last_collected_at,
    created_at,
    updated_at
FROM gugu.product
WHERE market = $1 AND external_product_id = $2
`

type FindProductByMarketAndExternalProductIDParams struct {
	Market            string `json:"market"`
	ExternalProductID string `json:"external_product_id"`
}

func (q *Queries) FindProductByMarketAndExternalProductID(ctx context.Context, arg FindProductByMarketAndExternalProductIDParams) (GuguProduct, error) {
	row := q.db.QueryRowContext(ctx, findProductByMarketAndExternalProductID, arg.Market, arg.ExternalProductID)
	var i GuguProduct
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.ExternalProductID,
		&i.OriginalUrl,
		&i.Title,
		&i.MainImageUrl,
		&i.CurrentPrice,
		&i.Currency,
		&i.ProductUrl,
		&i.PromotionLink,
		&i.CollectionSource,
		&i.LastCollectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProductsByIDs = `-- name: FindProductsByIDs :many
SELECT
    id,
    market,
    external_product_id,
    original_url,
    title,
    main_image_url,
    current_price,
    currency,
    product_url,
    promotion_link,
    collection_source,
    last_collected_at,
    created_at,
    updated_at
FROM gugu.product
WHERE id = ANY($1::text[])
`

func (q *Queries) FindProductsByIDs(ctx context.Context, dollar_1 []string) ([]GuguProduct, error) {
	rows, err := q.db.QueryContext(ctx, findProductsByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguProduct
	for rows.Next() {
		var i GuguProduct
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.CurrentPrice,
			&i.Currency,
			&i.ProductUrl,
			&i.PromotionLink,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByMarket = `-- name: ListProductsByMarket :many
SELECT
    id,
    market,
    external_product_id,
    original_url,
    title,
    main_image_url,
    current_price,
    currency,
    product_url,
    promotion_link,
    collection_source,
    last_collected_at,
    created_at,
    updated_at
FROM gugu.product
WHERE market = $1
ORDER BY created_at
`

func (q *Queries) ListProductsByMarket(ctx context.Context, market string) ([]GuguProduct, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByMarket, market)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguProduct
	for rows.Next() {
		var i GuguProduct
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ExternalProductID,
			&i.OriginalUrl,
			&i.Title,
			&i.MainImageUrl,
			&i.CurrentPrice,
			&i.Currency,
			&i.ProductUrl,
			&i.PromotionLink,
			&i.CollectionSource,
			&i.LastCollectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :execrows
UPDATE gugu.product
SET
    original_url = $2,
    title = $3,
    main_image_url = $4,
    current_price = $5,
    currency = $6,
    product_url = $7,
    promotion_link = $8,
    collection_source = $9,
    last_collected_at = $10,
    updated_at = $11
WHERE id = $1
`

type UpdateProductParams struct {
	ID               string    `json:"id"`
	OriginalUrl      string    `json:"original_url"`
	Title            string    `json:"title"`
	MainImageUrl     string    `json:"main_image_url"`
	CurrentPrice     string    `json:"current_price"`
	Currency         string    `json:"currency"`
	ProductUrl       string    `json:"product_url"`
	PromotionLink    string    `json:"promotion_link"`
	CollectionSource string    `json:"collection_source"`
	LastCollectedAt  time.Time `json:"last_collected_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProduct,
		arg.ID,
		arg.OriginalUrl,
		arg.Title,
		arg.MainImageUrl,
		arg.CurrentPrice,
		arg.Currency,
		arg.ProductUrl,
		arg.PromotionLink,
		arg.CollectionSource,
		arg.LastCollectedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
