// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sku_price_history.sql

package sqldb

import (
	"context"
	"time"
)

const createSKUPriceHistory = `-- name: CreateSKUPriceHistory :exec
INSERT INTO gugu.sku_price_history (
    sku_id,
    price,
    currency,
    recorded_at,
    change_value
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateSKUPriceHistoryParams struct {
	SkuID       string    `json:"sku_id"`
	Price       string    `json:"price"`
	Currency    string    `json:"currency"`
	RecordedAt  time.Time `json:"recorded_at"`
	ChangeValue string    `json:"change_value"`
}

func (q *Queries) CreateSKUPriceHistory(ctx context.Context, arg CreateSKUPriceHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createSKUPriceHistory,
		arg.SkuID,
		arg.Price,
		arg.Currency,
		arg.RecordedAt,
		arg.ChangeValue,
	)
	return err
}

const listSKUPriceHistoriesBySKUID = `-- name: ListSKUPriceHistoriesBySKUID :many
SELECT
    sku_id,
    price,
    currency,
    recorded_at,
    change_value
FROM gugu.sku_price_history
WHERE sku_id = $1 AND currency = $2
ORDER BY recorded_at DESC
`

type ListSKUPriceHistoriesBySKUIDParams struct {
	SkuID    string `json:"sku_id"`
	Currency string `json:"currency"`
}

type ListSKUPriceHistoriesBySKUIDRow struct {
	SkuID       string    `json:"sku_id"`
	Price       string    `json:"price"`
	Currency    string    `json:"currency"`
	RecordedAt  time.Time `json:"recorded_at"`
	ChangeValue string    `json:"change_value"`
}

func (q *Queries) ListSKUPriceHistoriesBySKUID(ctx context.Context, arg ListSKUPriceHistoriesBySKUIDParams) ([]ListSKUPriceHistoriesBySKUIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listSKUPriceHistoriesBySKUID, arg.SkuID, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSKUPriceHistoriesBySKUIDRow
	for rows.Next() {
		var i ListSKUPriceHistoriesBySKUIDRow
		if err := rows.Scan(
			&i.SkuID,
			&i.Price,
			&i.Currency,
			&i.RecordedAt,
			&i.ChangeValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
