// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sku_price_snapshot.sql

package sqldb

import (
	"context"
	"time"
)

const listSKUPriceSnapshotsByDateRange = `-- name: ListSKUPriceSnapshotsByDateRange :many
SELECT
    sku_id,
    snapshot_date,
    price,
    original_price,
    currency
FROM gugu.sku_price_snapshot
WHERE sku_id = $1
  AND currency = $2
  AND snapshot_date >= $3
  AND snapshot_date <= $4
ORDER BY snapshot_date ASC
`

type ListSKUPriceSnapshotsByDateRangeParams struct {
	SkuID          string    `json:"sku_id"`
	Currency       string    `json:"currency"`
	SnapshotDate   time.Time `json:"snapshot_date"`
	SnapshotDate_2 time.Time `json:"snapshot_date_2"`
}

func (q *Queries) ListSKUPriceSnapshotsByDateRange(ctx context.Context, arg ListSKUPriceSnapshotsByDateRangeParams) ([]GuguSkuPriceSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSKUPriceSnapshotsByDateRange,
		arg.SkuID,
		arg.Currency,
		arg.SnapshotDate,
		arg.SnapshotDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguSkuPriceSnapshot
	for rows.Next() {
		var i GuguSkuPriceSnapshot
		if err := rows.Scan(
			&i.SkuID,
			&i.SnapshotDate,
			&i.Price,
			&i.OriginalPrice,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSKUPriceSnapshot = `-- name: UpsertSKUPriceSnapshot :exec
INSERT INTO gugu.sku_price_snapshot (
    sku_id,
    snapshot_date,
    price,
    original_price,
    currency
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (sku_id, currency, snapshot_date) DO UPDATE SET
    price = EXCLUDED.price,
    original_price = EXCLUDED.original_price
`

type UpsertSKUPriceSnapshotParams struct {
	SkuID         string    `json:"sku_id"`
	SnapshotDate  time.Time `json:"snapshot_date"`
	Price         string    `json:"price"`
	OriginalPrice string    `json:"original_price"`
	Currency      string    `json:"currency"`
}

func (q *Queries) UpsertSKUPriceSnapshot(ctx context.Context, arg UpsertSKUPriceSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertSKUPriceSnapshot,
		arg.SkuID,
		arg.SnapshotDate,
		arg.Price,
		arg.OriginalPrice,
		arg.Currency,
	)
	return err
}
