// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracked_item.sql

package sqldb

import (
	"context"
	"time"
)

const createTrackedItem = `-- name: CreateTrackedItem :exec
INSERT INTO gugu.user_tracked_items (
    id,
    user_id,
    product_id,
    original_url,
    created_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateTrackedItemParams struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	ProductID   string    `json:"product_id"`
	OriginalUrl string    `json:"original_url"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateTrackedItem(ctx context.Context, arg CreateTrackedItemParams) error {
	_, err := q.db.ExecContext(ctx, createTrackedItem,
		arg.ID,
		arg.UserID,
		arg.ProductID,
		arg.OriginalUrl,
		arg.CreatedAt,
	)
	return err
}

const deleteTrackedItemByIDAndUserID = `-- name: DeleteTrackedItemByIDAndUserID :execrows
UPDATE gugu.user_tracked_items
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type DeleteTrackedItemByIDAndUserIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTrackedItemByIDAndUserID(ctx context.Context, arg DeleteTrackedItemByIDAndUserIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrackedItemByIDAndUserID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findTrackedItemByIDAndUserID = `-- name: FindTrackedItemByIDAndUserID :one
SELECT
    id,
    user_id,
    product_id,
    original_url,
    deleted_at,
    created_at
FROM gugu.user_tracked_items
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type FindTrackedItemByIDAndUserIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) FindTrackedItemByIDAndUserID(ctx context.Context, arg FindTrackedItemByIDAndUserIDParams) (GuguUserTrackedItem, error) {
	row := q.db.QueryRowContext(ctx, findTrackedItemByIDAndUserID, arg.ID, arg.UserID)
	var i GuguUserTrackedItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.OriginalUrl,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findTrackedItemByUserIDAndProductID = `-- name: FindTrackedItemByUserIDAndProductID :one
SELECT
    id,
    user_id,
    product_id,
    original_url,
    deleted_at,
    created_at
FROM gugu.user_tracked_items
WHERE user_id = $1 AND product_id = $2 AND deleted_at IS NULL
`

type FindTrackedItemByUserIDAndProductIDParams struct {
	UserID    string `json:"user_id"`
	ProductID string `json:"product_id"`
}

func (q *Queries) FindTrackedItemByUserIDAndProductID(ctx context.Context, arg FindTrackedItemByUserIDAndProductIDParams) (GuguUserTrackedItem, error) {
	row := q.db.QueryRowContext(ctx, findTrackedItemByUserIDAndProductID, arg.UserID, arg.ProductID)
	var i GuguUserTrackedItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.OriginalUrl,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTrackedItemsByUserID = `-- name: ListTrackedItemsByUserID :many
SELECT
    id,
    user_id,
    product_id,
    original_url,
    deleted_at,
    created_at
FROM gugu.user_tracked_items
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTrackedItemsByUserID(ctx context.Context, userID string) ([]GuguUserTrackedItem, error) {
	rows, err := q.db.QueryContext(ctx, listTrackedItemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguUserTrackedItem
	for rows.Next() {
		var i GuguUserTrackedItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.OriginalUrl,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
