// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracked_item.sql

package sqldb

import (
	"context"
	"database/sql"
	"time"
)

const createTrackedItem = `-- name: CreateTrackedItem :exec
INSERT INTO gugu.user_tracked_item (
    id,
    user_id,
    product_id,
    sku_id,
    original_url,
    view_external_product_id,
    preferred_language,
    tracking_scope,
    currency,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateTrackedItemParams struct {
	ID                    string         `json:"id"`
	UserID                string         `json:"user_id"`
	ProductID             string         `json:"product_id"`
	SkuID                 sql.NullString `json:"sku_id"`
	OriginalUrl           string         `json:"original_url"`
	ViewExternalProductID string         `json:"view_external_product_id"`
	PreferredLanguage     string         `json:"preferred_language"`
	TrackingScope         string         `json:"tracking_scope"`
	Currency              string         `json:"currency"`
	CreatedAt             time.Time      `json:"created_at"`
}

func (q *Queries) CreateTrackedItem(ctx context.Context, arg CreateTrackedItemParams) error {
	_, err := q.db.ExecContext(ctx, createTrackedItem,
		arg.ID,
		arg.UserID,
		arg.ProductID,
		arg.SkuID,
		arg.OriginalUrl,
		arg.ViewExternalProductID,
		arg.PreferredLanguage,
		arg.TrackingScope,
		arg.Currency,
		arg.CreatedAt,
	)
	return err
}

const createTrackedItemWatchSKU = `-- name: CreateTrackedItemWatchSKU :exec
INSERT INTO gugu.user_tracked_item_watch_sku (
    tracked_item_id,
    sku_id
) VALUES (
    $1, $2
)
ON CONFLICT (tracked_item_id, sku_id) DO NOTHING
`

type CreateTrackedItemWatchSKUParams struct {
	TrackedItemID string `json:"tracked_item_id"`
	SkuID         string `json:"sku_id"`
}

func (q *Queries) CreateTrackedItemWatchSKU(ctx context.Context, arg CreateTrackedItemWatchSKUParams) error {
	_, err := q.db.ExecContext(ctx, createTrackedItemWatchSKU, arg.TrackedItemID, arg.SkuID)
	return err
}

const deleteTrackedItemByIDAndUserID = `-- name: DeleteTrackedItemByIDAndUserID :execrows
UPDATE gugu.user_tracked_item
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type DeleteTrackedItemByIDAndUserIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTrackedItemByIDAndUserID(ctx context.Context, arg DeleteTrackedItemByIDAndUserIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrackedItemByIDAndUserID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTrackedItemWatchSKUs = `-- name: DeleteTrackedItemWatchSKUs :exec
DELETE FROM gugu.user_tracked_item_watch_sku
WHERE tracked_item_id = $1
`

func (q *Queries) DeleteTrackedItemWatchSKUs(ctx context.Context, trackedItemID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackedItemWatchSKUs, trackedItemID)
	return err
}

const findTrackedItemByIDAndUserID = `-- name: FindTrackedItemByIDAndUserID :one
SELECT
    id,
    user_id,
    product_id,
    sku_id,
    original_url,
    view_external_product_id,
    preferred_language,
    tracking_scope,
    currency,
    deleted_at,
    created_at
FROM gugu.user_tracked_item
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type FindTrackedItemByIDAndUserIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) FindTrackedItemByIDAndUserID(ctx context.Context, arg FindTrackedItemByIDAndUserIDParams) (GuguUserTrackedItem, error) {
	row := q.db.QueryRowContext(ctx, findTrackedItemByIDAndUserID, arg.ID, arg.UserID)
	var i GuguUserTrackedItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.SkuID,
		&i.OriginalUrl,
		&i.ViewExternalProductID,
		&i.PreferredLanguage,
		&i.TrackingScope,
		&i.Currency,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findTrackedItemByUserIDAndProductID = `-- name: FindTrackedItemByUserIDAndProductID :one
SELECT
    id,
    user_id,
    product_id,
    sku_id,
    original_url,
    view_external_product_id,
    preferred_language,
    tracking_scope,
    currency,
    deleted_at,
    created_at
FROM gugu.user_tracked_item
WHERE user_id = $1 AND product_id = $2 AND deleted_at IS NULL
`

type FindTrackedItemByUserIDAndProductIDParams struct {
	UserID    string `json:"user_id"`
	ProductID string `json:"product_id"`
}

func (q *Queries) FindTrackedItemByUserIDAndProductID(ctx context.Context, arg FindTrackedItemByUserIDAndProductIDParams) (GuguUserTrackedItem, error) {
	row := q.db.QueryRowContext(ctx, findTrackedItemByUserIDAndProductID, arg.UserID, arg.ProductID)
	var i GuguUserTrackedItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.SkuID,
		&i.OriginalUrl,
		&i.ViewExternalProductID,
		&i.PreferredLanguage,
		&i.TrackingScope,
		&i.Currency,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTrackedItemsByUserID = `-- name: ListTrackedItemsByUserID :many
SELECT
    id,
    user_id,
    product_id,
    sku_id,
    original_url,
    view_external_product_id,
    preferred_language,
    tracking_scope,
    currency,
    deleted_at,
    created_at
FROM gugu.user_tracked_item
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTrackedItemsByUserID(ctx context.Context, userID string) ([]GuguUserTrackedItem, error) {
	rows, err := q.db.QueryContext(ctx, listTrackedItemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguUserTrackedItem
	for rows.Next() {
		var i GuguUserTrackedItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.SkuID,
			&i.OriginalUrl,
			&i.ViewExternalProductID,
			&i.PreferredLanguage,
			&i.TrackingScope,
			&i.Currency,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedItemsByUserIDFirstPage = `-- name: ListTrackedItemsByUserIDFirstPage :many
SELECT
    id,
    user_id,
    product_id,
    sku_id,
    original_url,
    view_external_product_id,
    preferred_language,
    tracking_scope,
    currency,
    deleted_at,
    created_at
FROM gugu.user_tracked_item
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListTrackedItemsByUserIDFirstPageParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListTrackedItemsByUserIDFirstPage(ctx context.Context, arg ListTrackedItemsByUserIDFirstPageParams) ([]GuguUserTrackedItem, error) {
	rows, err := q.db.QueryContext(ctx, listTrackedItemsByUserIDFirstPage, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguUserTrackedItem
	for rows.Next() {
		var i GuguUserTrackedItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.SkuID,
			&i.OriginalUrl,
			&i.ViewExternalProductID,
			&i.PreferredLanguage,
			&i.TrackingScope,
			&i.Currency,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedItemsByUserIDWithCursor = `-- name: ListTrackedItemsByUserIDWithCursor :many
SELECT
    id,
    user_id,
    product_id,
    sku_id,
    original_url,
    view_external_product_id,
    preferred_language,
    tracking_scope,
    currency,
    deleted_at,
    created_at
FROM gugu.user_tracked_item
WHERE user_id = $1
  AND deleted_at IS NULL
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListTrackedItemsByUserIDWithCursorParams struct {
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ID        string    `json:"id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListTrackedItemsByUserIDWithCursor(ctx context.Context, arg ListTrackedItemsByUserIDWithCursorParams) ([]GuguUserTrackedItem, error) {
	rows, err := q.db.QueryContext(ctx, listTrackedItemsByUserIDWithCursor,
		arg.UserID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuguUserTrackedItem
	for rows.Next() {
		var i GuguUserTrackedItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.SkuID,
			&i.OriginalUrl,
			&i.ViewExternalProductID,
			&i.PreferredLanguage,
			&i.TrackingScope,
			&i.Currency,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrackedItemPreferredLanguage = `-- name: UpdateTrackedItemPreferredLanguage :execrows
UPDATE gugu.user_tracked_item
SET preferred_language = $3
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type UpdateTrackedItemPreferredLanguageParams struct {
	ID                string `json:"id"`
	UserID            string `json:"user_id"`
	PreferredLanguage string `json:"preferred_language"`
}

func (q *Queries) UpdateTrackedItemPreferredLanguage(ctx context.Context, arg UpdateTrackedItemPreferredLanguageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTrackedItemPreferredLanguage, arg.ID, arg.UserID, arg.PreferredLanguage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTrackedItemSKU = `-- name: UpdateTrackedItemSKU :execrows
UPDATE gugu.user_tracked_item
SET sku_id = $3
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type UpdateTrackedItemSKUParams struct {
	ID     string         `json:"id"`
	UserID string         `json:"user_id"`
	SkuID  sql.NullString `json:"sku_id"`
}

func (q *Queries) UpdateTrackedItemSKU(ctx context.Context, arg UpdateTrackedItemSKUParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTrackedItemSKU, arg.ID, arg.UserID, arg.SkuID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTrackedItemTrackingScope = `-- name: UpdateTrackedItemTrackingScope :execrows
UPDATE gugu.user_tracked_item
SET tracking_scope = $3
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type UpdateTrackedItemTrackingScopeParams struct {
	ID            string `json:"id"`
	UserID        string `json:"user_id"`
	TrackingScope string `json:"tracking_scope"`
}

func (q *Queries) UpdateTrackedItemTrackingScope(ctx context.Context, arg UpdateTrackedItemTrackingScopeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTrackedItemTrackingScope, arg.ID, arg.UserID, arg.TrackingScope)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
