// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqldb

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO gugu.app_user (
    id,
    email,
    display_name,
    password_hash,
    auth_source,
    email_verified,
    email_verified_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateUserParams struct {
	ID              string       `json:"id"`
	Email           string       `json:"email"`
	DisplayName     string       `json:"display_name"`
	PasswordHash    string       `json:"password_hash"`
	AuthSource      string       `json:"auth_source"`
	EmailVerified   bool         `json:"email_verified"`
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
	CreatedAt       time.Time    `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.AuthSource,
		arg.EmailVerified,
		arg.EmailVerifiedAt,
		arg.CreatedAt,
	)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT
    id,
    email,
    display_name,
    password_hash,
    auth_source,
    email_verified,
    email_verified_at,
    created_at
FROM gugu.app_user
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (GuguAppUser, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i GuguAppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AuthSource,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT
    id,
    email,
    display_name,
    password_hash,
    auth_source,
    email_verified,
    email_verified_at,
    created_at
FROM gugu.app_user
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (GuguAppUser, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i GuguAppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AuthSource,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :execrows
UPDATE gugu.app_user
SET
    email_verified = TRUE,
    email_verified_at = $2
WHERE id = $1
`

type MarkUserEmailVerifiedParams struct {
	ID              string       `json:"id"`
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUserEmailVerified, arg.ID, arg.EmailVerifiedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
